apiVersion: v1
kind: ConfigMap
metadata:
  name: config_map
data:
  mysql-wr-server: |
    host: localhost
    port: 3306
    username: root
    password: 123
    db_user: db_user
    db_listing: db_listing
    db_order: db_order
  mysql-rd-server: |
    host: localhost
    port: 3306
    username: root
    password: 123
    db_user: db_user
    db_listing: db_listing
    db_order: db_order
  registry-server:
    host: consul.default.svc.cluster
    port: 8500
