---
apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    name: consul
spec:
  ports:
    - name: http
      port: 8500
      targetPort: 8500
  selector:
    app: consul
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul
spec:
  serviceName: consul
  replicas: 3
  template:
    metadata:
      labels:
        app: consul
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: consul
        image: consul:latest
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        args:
          - "agent"
          - "-data-dir=/var/lib/consul"
          - "-server"
          - "-bootstrap-expect=2"
          - "-bind=0.0.0.0"
          - "-advertise=$(POD_IP)"
          - "-client=0.0.0.0"
          - "-retry-join=consul-0.consul.default.svc.cluster.local"
          - "-retry-join=consul-1.consul.default.svc.cluster.local"
        volumeMounts:
          - mountPath: /var/lib/consul
            name: data
        ports:
          - containerPort: 8500
            name: ui-port
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/sh
                - -c
                - consul leave
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

