apiVersion: v1
kind: Service # 类型为Service
metadata:
  name: order # 定义Service的name
spec:
  ports:
  - port
    name: http
    targetPort: 8080
    protocol: TCP
  selector:
    app: order

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: order:latest
        ports:
        - containerPort: 8080

