apiVersion: v1
kind: Service # 类型为Service
metadata:
  name: user # 定义Service的name
spec:
  ports:
  - port
    name: http
    targetPort: 8080
    protocol: TCP
  selector:
    app: user

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: user:latest
        ports:
        - containerPort: 8080
        env:
          name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: config_map
              key: mysql-wr-server.host
          name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: config_map
              key: mysql-wr-server.port
          name: MYSQL_USRNAME
          valueFrom:
            configMapKeyRef:
              name: config_map
              key: mysql-wr-server.username
          name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: config_map
              key: mysql-wr-server.password
          name: MYSQL_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: config_map
              key: mysql-wr-server.db_user
          name: REGISTRY_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: config_map
              key: registry_server.host
          name: REGISTRY_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: config_map
              key: registry_server.port
