// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	User
	UsersRequest
	UsersSearchRequest
	UserRequest
	UsersResponse
	UserResponse
	Store
	StoresRequest
	StoresSearchRequest
	StoreRequest
	StoresResponse
	StoreResponse
	Customer
	CustomersRequest
	CustomersSearchRequest
	CustomerRequest
	CustomersResponse
	CustomerResponse
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id    int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Phone string `protobuf:"bytes,3,opt,name=phone" json:"phone,omitempty"`
	Email string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Role  int32  `protobuf:"varint,5,opt,name=role" json:"role,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

type UsersRequest struct {
	Ids []int32 `protobuf:"varint,1,rep,packed,name=ids" json:"ids,omitempty"`
}

func (m *UsersRequest) Reset()                    { *m = UsersRequest{} }
func (m *UsersRequest) String() string            { return proto.CompactTextString(m) }
func (*UsersRequest) ProtoMessage()               {}
func (*UsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UsersRequest) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type UsersSearchRequest struct {
	Names []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
}

func (m *UsersSearchRequest) Reset()                    { *m = UsersSearchRequest{} }
func (m *UsersSearchRequest) String() string            { return proto.CompactTextString(m) }
func (*UsersSearchRequest) ProtoMessage()               {}
func (*UsersSearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UsersSearchRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type UserRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *UserRequest) Reset()                    { *m = UserRequest{} }
func (m *UserRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()               {}
func (*UserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UsersResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *UsersResponse) Reset()                    { *m = UsersResponse{} }
func (m *UsersResponse) String() string            { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()               {}
func (*UsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UserResponse) Reset()                    { *m = UserResponse{} }
func (m *UserResponse) String() string            { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()               {}
func (*UserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Store struct {
	Id      int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
}

func (m *Store) Reset()                    { *m = Store{} }
func (m *Store) String() string            { return proto.CompactTextString(m) }
func (*Store) ProtoMessage()               {}
func (*Store) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Store) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Store) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Store) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type StoresRequest struct {
	Ids []int32 `protobuf:"varint,1,rep,packed,name=ids" json:"ids,omitempty"`
}

func (m *StoresRequest) Reset()                    { *m = StoresRequest{} }
func (m *StoresRequest) String() string            { return proto.CompactTextString(m) }
func (*StoresRequest) ProtoMessage()               {}
func (*StoresRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *StoresRequest) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type StoresSearchRequest struct {
	Titles []string `protobuf:"bytes,1,rep,name=titles" json:"titles,omitempty"`
}

func (m *StoresSearchRequest) Reset()                    { *m = StoresSearchRequest{} }
func (m *StoresSearchRequest) String() string            { return proto.CompactTextString(m) }
func (*StoresSearchRequest) ProtoMessage()               {}
func (*StoresSearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *StoresSearchRequest) GetTitles() []string {
	if m != nil {
		return m.Titles
	}
	return nil
}

type StoreRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *StoreRequest) Reset()                    { *m = StoreRequest{} }
func (m *StoreRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreRequest) ProtoMessage()               {}
func (*StoreRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *StoreRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type StoresResponse struct {
	Stores []*Store `protobuf:"bytes,1,rep,name=stores" json:"stores,omitempty"`
}

func (m *StoresResponse) Reset()                    { *m = StoresResponse{} }
func (m *StoresResponse) String() string            { return proto.CompactTextString(m) }
func (*StoresResponse) ProtoMessage()               {}
func (*StoresResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *StoresResponse) GetStores() []*Store {
	if m != nil {
		return m.Stores
	}
	return nil
}

type StoreResponse struct {
	Store *Store `protobuf:"bytes,1,opt,name=store" json:"store,omitempty"`
}

func (m *StoreResponse) Reset()                    { *m = StoreResponse{} }
func (m *StoreResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreResponse) ProtoMessage()               {}
func (*StoreResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *StoreResponse) GetStore() *Store {
	if m != nil {
		return m.Store
	}
	return nil
}

type Customer struct {
	Id      int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	StoreId int32  `protobuf:"varint,3,opt,name=store_id,json=storeId" json:"store_id,omitempty"`
	UserId  int32  `protobuf:"varint,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *Customer) Reset()                    { *m = Customer{} }
func (m *Customer) String() string            { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()               {}
func (*Customer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Customer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Customer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Customer) GetStoreId() int32 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *Customer) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CustomersRequest struct {
	Ids []int32 `protobuf:"varint,1,rep,packed,name=ids" json:"ids,omitempty"`
}

func (m *CustomersRequest) Reset()                    { *m = CustomersRequest{} }
func (m *CustomersRequest) String() string            { return proto.CompactTextString(m) }
func (*CustomersRequest) ProtoMessage()               {}
func (*CustomersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CustomersRequest) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type CustomersSearchRequest struct {
	Names    []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
	StoreIds []int32  `protobuf:"varint,2,rep,packed,name=store_ids,json=storeIds" json:"store_ids,omitempty"`
	UserId   int32    `protobuf:"varint,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *CustomersSearchRequest) Reset()                    { *m = CustomersSearchRequest{} }
func (m *CustomersSearchRequest) String() string            { return proto.CompactTextString(m) }
func (*CustomersSearchRequest) ProtoMessage()               {}
func (*CustomersSearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CustomersSearchRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *CustomersSearchRequest) GetStoreIds() []int32 {
	if m != nil {
		return m.StoreIds
	}
	return nil
}

func (m *CustomersSearchRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CustomerRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CustomerRequest) Reset()                    { *m = CustomerRequest{} }
func (m *CustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*CustomerRequest) ProtoMessage()               {}
func (*CustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CustomerRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CustomersResponse struct {
	Stores []*Store `protobuf:"bytes,1,rep,name=stores" json:"stores,omitempty"`
}

func (m *CustomersResponse) Reset()                    { *m = CustomersResponse{} }
func (m *CustomersResponse) String() string            { return proto.CompactTextString(m) }
func (*CustomersResponse) ProtoMessage()               {}
func (*CustomersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *CustomersResponse) GetStores() []*Store {
	if m != nil {
		return m.Stores
	}
	return nil
}

type CustomerResponse struct {
	Store *Store `protobuf:"bytes,1,opt,name=store" json:"store,omitempty"`
}

func (m *CustomerResponse) Reset()                    { *m = CustomerResponse{} }
func (m *CustomerResponse) String() string            { return proto.CompactTextString(m) }
func (*CustomerResponse) ProtoMessage()               {}
func (*CustomerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *CustomerResponse) GetStore() *Store {
	if m != nil {
		return m.Store
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*UsersRequest)(nil), "UsersRequest")
	proto.RegisterType((*UsersSearchRequest)(nil), "UsersSearchRequest")
	proto.RegisterType((*UserRequest)(nil), "UserRequest")
	proto.RegisterType((*UsersResponse)(nil), "UsersResponse")
	proto.RegisterType((*UserResponse)(nil), "UserResponse")
	proto.RegisterType((*Store)(nil), "Store")
	proto.RegisterType((*StoresRequest)(nil), "StoresRequest")
	proto.RegisterType((*StoresSearchRequest)(nil), "StoresSearchRequest")
	proto.RegisterType((*StoreRequest)(nil), "StoreRequest")
	proto.RegisterType((*StoresResponse)(nil), "StoresResponse")
	proto.RegisterType((*StoreResponse)(nil), "StoreResponse")
	proto.RegisterType((*Customer)(nil), "Customer")
	proto.RegisterType((*CustomersRequest)(nil), "CustomersRequest")
	proto.RegisterType((*CustomersSearchRequest)(nil), "CustomersSearchRequest")
	proto.RegisterType((*CustomerRequest)(nil), "CustomerRequest")
	proto.RegisterType((*CustomersResponse)(nil), "CustomersResponse")
	proto.RegisterType((*CustomerResponse)(nil), "CustomerResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Service service

type ServiceClient interface {
	GetUsers(ctx context.Context, in *UsersRequest, opts ...client.CallOption) (*UsersResponse, error)
	SearchUsers(ctx context.Context, in *UsersSearchRequest, opts ...client.CallOption) (*UsersResponse, error)
	GetUser(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserResponse, error)
	GetStores(ctx context.Context, in *StoresRequest, opts ...client.CallOption) (*StoresResponse, error)
	SearchStores(ctx context.Context, in *StoresSearchRequest, opts ...client.CallOption) (*StoresResponse, error)
	GetStore(ctx context.Context, in *StoreRequest, opts ...client.CallOption) (*StoreResponse, error)
	GetCustomers(ctx context.Context, in *CustomersRequest, opts ...client.CallOption) (*CustomersResponse, error)
	SearchCustomers(ctx context.Context, in *CustomersSearchRequest, opts ...client.CallOption) (*CustomersResponse, error)
	GetCustomer(ctx context.Context, in *CustomerRequest, opts ...client.CallOption) (*CustomerResponse, error)
}

type serviceClient struct {
	c           client.Client
	serviceName string
}

func NewServiceClient(serviceName string, c client.Client) ServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "service"
	}
	return &serviceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *serviceClient) GetUsers(ctx context.Context, in *UsersRequest, opts ...client.CallOption) (*UsersResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Service.GetUsers", in)
	out := new(UsersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) SearchUsers(ctx context.Context, in *UsersSearchRequest, opts ...client.CallOption) (*UsersResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Service.SearchUsers", in)
	out := new(UsersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetUser(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Service.GetUser", in)
	out := new(UserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetStores(ctx context.Context, in *StoresRequest, opts ...client.CallOption) (*StoresResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Service.GetStores", in)
	out := new(StoresResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) SearchStores(ctx context.Context, in *StoresSearchRequest, opts ...client.CallOption) (*StoresResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Service.SearchStores", in)
	out := new(StoresResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetStore(ctx context.Context, in *StoreRequest, opts ...client.CallOption) (*StoreResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Service.GetStore", in)
	out := new(StoreResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetCustomers(ctx context.Context, in *CustomersRequest, opts ...client.CallOption) (*CustomersResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Service.GetCustomers", in)
	out := new(CustomersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) SearchCustomers(ctx context.Context, in *CustomersSearchRequest, opts ...client.CallOption) (*CustomersResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Service.SearchCustomers", in)
	out := new(CustomersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetCustomer(ctx context.Context, in *CustomerRequest, opts ...client.CallOption) (*CustomerResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Service.GetCustomer", in)
	out := new(CustomerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceHandler interface {
	GetUsers(context.Context, *UsersRequest, *UsersResponse) error
	SearchUsers(context.Context, *UsersSearchRequest, *UsersResponse) error
	GetUser(context.Context, *UserRequest, *UserResponse) error
	GetStores(context.Context, *StoresRequest, *StoresResponse) error
	SearchStores(context.Context, *StoresSearchRequest, *StoresResponse) error
	GetStore(context.Context, *StoreRequest, *StoreResponse) error
	GetCustomers(context.Context, *CustomersRequest, *CustomersResponse) error
	SearchCustomers(context.Context, *CustomersSearchRequest, *CustomersResponse) error
	GetCustomer(context.Context, *CustomerRequest, *CustomerResponse) error
}

func RegisterServiceHandler(s server.Server, hdlr ServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Service{hdlr}, opts...))
}

type Service struct {
	ServiceHandler
}

func (h *Service) GetUsers(ctx context.Context, in *UsersRequest, out *UsersResponse) error {
	return h.ServiceHandler.GetUsers(ctx, in, out)
}

func (h *Service) SearchUsers(ctx context.Context, in *UsersSearchRequest, out *UsersResponse) error {
	return h.ServiceHandler.SearchUsers(ctx, in, out)
}

func (h *Service) GetUser(ctx context.Context, in *UserRequest, out *UserResponse) error {
	return h.ServiceHandler.GetUser(ctx, in, out)
}

func (h *Service) GetStores(ctx context.Context, in *StoresRequest, out *StoresResponse) error {
	return h.ServiceHandler.GetStores(ctx, in, out)
}

func (h *Service) SearchStores(ctx context.Context, in *StoresSearchRequest, out *StoresResponse) error {
	return h.ServiceHandler.SearchStores(ctx, in, out)
}

func (h *Service) GetStore(ctx context.Context, in *StoreRequest, out *StoreResponse) error {
	return h.ServiceHandler.GetStore(ctx, in, out)
}

func (h *Service) GetCustomers(ctx context.Context, in *CustomersRequest, out *CustomersResponse) error {
	return h.ServiceHandler.GetCustomers(ctx, in, out)
}

func (h *Service) SearchCustomers(ctx context.Context, in *CustomersSearchRequest, out *CustomersResponse) error {
	return h.ServiceHandler.SearchCustomers(ctx, in, out)
}

func (h *Service) GetCustomer(ctx context.Context, in *CustomerRequest, out *CustomerResponse) error {
	return h.ServiceHandler.GetCustomer(ctx, in, out)
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x49, 0x6f, 0xdb, 0x3c,
	0x10, 0xf5, 0x46, 0x2f, 0x63, 0x5b, 0xb6, 0x27, 0x46, 0xa2, 0x28, 0xdf, 0x17, 0x38, 0x44, 0x0f,
	0xee, 0x12, 0x22, 0x48, 0x02, 0xf4, 0x5a, 0xa0, 0x07, 0x23, 0x57, 0x19, 0x3d, 0x17, 0x4e, 0x44,
	0x20, 0x2a, 0x6c, 0xcb, 0x15, 0xe5, 0xfe, 0xdb, 0xfe, 0x97, 0x82, 0x43, 0x52, 0x91, 0xbc, 0x04,
	0xbe, 0x69, 0x86, 0x6f, 0xe6, 0x0d, 0x1f, 0xdf, 0x08, 0x60, 0xab, 0x64, 0x2a, 0x36, 0x69, 0x92,
	0x25, 0xfc, 0x17, 0x34, 0x7e, 0x28, 0x99, 0xa2, 0x07, 0xb5, 0x38, 0xf2, 0xab, 0x93, 0xea, 0x94,
	0x85, 0xb5, 0x38, 0x42, 0x84, 0xc6, 0x7a, 0xb1, 0x92, 0x7e, 0x6d, 0x52, 0x9d, 0x76, 0x42, 0xfa,
	0xc6, 0x31, 0xb0, 0xcd, 0x6b, 0xb2, 0x96, 0x7e, 0x9d, 0x92, 0x26, 0xd0, 0x59, 0xb9, 0x5a, 0xc4,
	0x4b, 0xbf, 0x61, 0xb2, 0x14, 0xe8, 0xfa, 0x34, 0x59, 0x4a, 0x9f, 0x51, 0x47, 0xfa, 0xe6, 0x13,
	0xe8, 0x69, 0x2e, 0x15, 0xca, 0xdf, 0x5b, 0xa9, 0x32, 0x1c, 0x42, 0x3d, 0x8e, 0x94, 0x5f, 0x9d,
	0xd4, 0xa7, 0x2c, 0xd4, 0x9f, 0xfc, 0x13, 0x20, 0x21, 0xe6, 0x72, 0x91, 0xbe, 0xbc, 0x3a, 0xdc,
	0x18, 0x98, 0xe6, 0x37, 0xc8, 0x4e, 0x68, 0x02, 0xfe, 0x3f, 0x74, 0x35, 0xd6, 0x81, 0x76, 0x2e,
	0xc0, 0xbf, 0x40, 0xdf, 0x92, 0xa9, 0x4d, 0xb2, 0x56, 0x12, 0xaf, 0x80, 0xe9, 0x7b, 0x9b, 0x2e,
	0xdd, 0x7b, 0x26, 0xa8, 0xda, 0xe4, 0xf8, 0x47, 0x33, 0x5a, 0x0e, 0xbe, 0x84, 0x86, 0x3e, 0xa0,
	0x7e, 0x39, 0x96, 0x52, 0x7c, 0x06, 0x6c, 0x9e, 0x25, 0xa9, 0xdc, 0x93, 0x6c, 0x0c, 0x2c, 0x8b,
	0xb3, 0xa5, 0xd3, 0xcc, 0x04, 0xe8, 0x43, 0x6b, 0x11, 0x45, 0xa9, 0x54, 0xca, 0xca, 0xe6, 0x42,
	0x7e, 0x03, 0x7d, 0x6a, 0xf4, 0x8e, 0x1e, 0xb7, 0x70, 0x66, 0x20, 0x65, 0x41, 0xce, 0xa1, 0x49,
	0xcd, 0x9d, 0x22, 0x36, 0xe2, 0xd7, 0xd0, 0x23, 0xf8, 0x31, 0x4d, 0xee, 0xc0, 0x73, 0x8c, 0xf6,
	0x9e, 0xd7, 0xd0, 0x54, 0x94, 0xb1, 0xaa, 0x34, 0x85, 0x69, 0x60, 0xb3, 0xfc, 0xd6, 0xce, 0x98,
	0x17, 0xfc, 0x07, 0x8c, 0x8e, 0xac, 0x32, 0x0e, 0x6f, 0x92, 0xfc, 0x19, 0xda, 0xdf, 0xb7, 0x2a,
	0x4b, 0x56, 0x27, 0x3a, 0xea, 0x12, 0xda, 0x54, 0xf8, 0x33, 0x8e, 0x48, 0x1d, 0x16, 0xb6, 0x28,
	0x7e, 0x8a, 0xf0, 0x02, 0x5a, 0x5a, 0x6e, 0x7d, 0xd2, 0xa0, 0x93, 0xa6, 0x0e, 0x9f, 0x22, 0xfe,
	0x01, 0x86, 0x8e, 0xe3, 0x1d, 0xe5, 0x22, 0x38, 0xcf, 0x51, 0x27, 0xb8, 0x09, 0xaf, 0xa0, 0xe3,
	0x26, 0x51, 0x7e, 0x8d, 0xfa, 0xb4, 0xed, 0x28, 0xaa, 0x38, 0x4b, 0xbd, 0x34, 0xcb, 0x0d, 0x0c,
	0x1c, 0xcb, 0x31, 0xcd, 0x1f, 0x60, 0x54, 0x18, 0xf7, 0x44, 0xd9, 0xef, 0xde, 0xee, 0x78, 0x9a,
	0xf2, 0xf7, 0x7f, 0xeb, 0xd0, 0x9a, 0xcb, 0xf4, 0x4f, 0xfc, 0x22, 0xf1, 0x33, 0xb4, 0x67, 0x32,
	0x23, 0xf7, 0x63, 0x5f, 0x14, 0x57, 0x2e, 0xf0, 0x44, 0x69, 0x29, 0x78, 0x05, 0x1f, 0xa1, 0x6b,
	0xf4, 0x31, 0xf8, 0x33, 0xb1, 0xbf, 0x80, 0x07, 0xaa, 0xa6, 0xd0, 0xb2, 0x14, 0xd8, 0x13, 0x85,
	0x35, 0x0c, 0xfa, 0xa2, 0xb8, 0x47, 0xbc, 0x82, 0x02, 0x3a, 0x33, 0x99, 0x19, 0xdb, 0xa1, 0x27,
	0x4a, 0x8e, 0x0f, 0x06, 0xa2, 0xec, 0x47, 0x5e, 0xc1, 0xaf, 0xd0, 0x33, 0xe4, 0xb6, 0x64, 0x2c,
	0x0e, 0x6c, 0xc0, 0xa1, 0x42, 0x73, 0x6b, 0xb3, 0x9a, 0x7d, 0x51, 0xdc, 0x83, 0xc0, 0x13, 0x25,
	0x13, 0x1b, 0x96, 0x99, 0xcc, 0xf2, 0x87, 0xc1, 0x91, 0xd8, 0xf5, 0x54, 0x80, 0x62, 0xef, 0xdd,
	0x78, 0x05, 0xbf, 0xc1, 0xc0, 0x4c, 0xf2, 0x56, 0x7b, 0x21, 0x0e, 0x3b, 0xed, 0x48, 0x87, 0x47,
	0xe8, 0x16, 0xa8, 0x71, 0x28, 0x76, 0x1c, 0x14, 0x8c, 0xc4, 0xee, 0xdb, 0xf3, 0xca, 0x73, 0x93,
	0x7e, 0xd7, 0x0f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x91, 0x57, 0x53, 0x9e, 0xbc, 0x05, 0x00,
	0x00,
}
